### ISSUE TITLE
Add disabled property

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-tooltip#53] opened 2016-01-27 17:23 UTC
In some contexts, it would be useful to temporarily disable the tooltip (prevent it from appearing).  Imagine a WYSIWYG editor where you can hover over a tool button to see the tooltip.  If that tool is currently disabled, it'd be nice to be able to disable its tooltip as well.

**Comment by miztroh** [comment] 2016-01-27 17:27
For now, I can hack around this by adding a ``disabled`` attribute and using the following style rule:

```
paper-tooltip[disabled] {
	visibility: hidden;
}
```

Note that you have to use ``visibility`` and not ``hidden``, because hiding a ``paper-tooltip`` causes console errors the next time it activates.

**Comment by notwaldorf** [comment] 2016-01-28 03:12
I think the main problem is your target, not the tooltip: when your target is disabled, it should set `pointer-events:none`. Then, `mouseover` won't actually fire, and the tooltip will (correctly) not show up.

Here's a jsbin that shows this, with `paper-button` (which sets `pointer-events:none` when disabled: https://github.com/PolymerElements/paper-button/blob/master/paper-button.html#L126)

Do you have a jsbin with an example that reproduces the console error you see? Otherwise I think we can close this issue

**Comment by notwaldorf** [comment] 2016-01-28 04:55
Sent a PR to fix the crash. In any case, as mentioned before, I don't think the tooltip needs a `disabled` attribute since it can correctly use the target's. Closing.

**Closed by notwaldorf** 2016-01-28 04:55 UTC

**Comment by miztroh** [comment] 2016-01-28 05:05
@notwaldorf Thanks for the tip.  I assume this will correct my issue.  I haven't yet set my targets manually, so I believe the tooltip is defaulting to the parent node.  I set disabled on the parent node, but that element doesn't have CSS for pointer events while disabled.  I'll setup my tooltips to target their sibling paper-icon-buttons.  That should take care of it for me.
