### ISSUE TITLE
Tooltips do not position or size themselves intelligently

### ISSUE THREAD

**Issue by stevenjb** [PolymerElements/paper-tooltip#34] opened 2015-09-18 18:54 UTC
Long tooltips on a small screen can get cut off. There doesn't seem to be much if any positioning or sizing logic to address this.

![screenshot from 2015-09-18 11 52 47](https://cloud.githubusercontent.com/assets/8367889/9968194/f6718748-5dfb-11e5-8c10-612c1d463b1b.png)

**Comment by stevenjb** [comment] 2015-09-18 18:55
@tjsavage @dbeam

**Comment by samccone** [comment] 2015-09-18 20:31
:+1: good spot @stevenjb 

This should be fairly straight forward to resolve,we will just have to intelligently "center" the tooltip relative to the width.

**Comment by notwaldorf** [comment] 2015-09-21 17:12
@stevenjb @dbeam @samccone As of the latest release, `paper-tooltip` has an attribute called `fit-to-visible-bounds`. If set, this should address this (I didn't set it to be true by default since I was worried it was maybe too aggressive, but I'm not opposed to changing that). Can you give it a try and let me know if that works? Thanks!

**Comment by notwaldorf** [comment] 2015-10-07 17:35
Is this still an issue, or can I close this?

**Comment by notwaldorf** [comment] 2015-10-20 19:17
Closing this since there's no activity.

**Closed by notwaldorf** 2015-10-20 19:17 UTC
Labels: pending-response

**Comment by denishamann** [comment] 2017-05-19 13:57
Long text in fact are left cut off on small screen like iPhone 5, even with the fitToVisibleBounds attribute set to true. 
The case can be reproduced by taking the demo on webcomponents.org, make a text longer, pass to developper view mode of an iphone 5 (320x568).

![paper-tooltip-issue](https://cloud.githubusercontent.com/assets/15311371/26250905/d850e192-3cab-11e7-9470-2fe91ce2c928.png)


Am I doing something wrong ?
